---
driver_plugin: vagrant

driver_config:
  network:
    - ["private_network", {ip: "192.168.99.20"}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[railsapp::rails]
